spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

    properties:
      hibernate.jdbc.batch_size: 20

  sql:
    init:
      mode: ALWAYS
      schema-locations:
        - classpath:sql/schema.sql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ml6q5bzm.auth0.com/

springdoc:
  paths-to-exclude: /warmup, /warmup-db